---
title: "Notes re: R package"
author: "Sam Levin"
date: "May 19, 2018"
output: github_document
---

## Must fix before submitting

* Bug in report_dictionary that causes species epithets to be listed under
structure rather than species (only observed in R 3.5, but may be an issue
going back further)

* We need more/updated unit tests.  

* `lter_maps` uses `aes_`. ggplot2 > 2.3 deprecates this in favor of tidyeval

* `parse_to_sql_search` uses `sql_translate_`. Check if this is deprecated
in favor of tidyeval syntax

* `tallies` in `summary_popler` contains underscored verbs

* add `pplr`- prefix for all exported functions
    + e.g. `browse` becomes `pplr_browse`

* standardize argument names
    + e.g. `input` and `browsed` mean the same thing (object returned by `browse`)
    
* Once graph is done, determine if all exports are necessary

* I will update this as I have time/find more


## Things that don't need fixing, but are worth thinking about

* Does it make more sense to initiate the connection to popler at the beginning
of each session rather than the initiation of a query? might reduce data retrieval
times for users with high request rate. I don't think this is particularly pressing
before submitting

* currently, *cov_unpack* returns a data frame with twice as many columns 
as covariates, storing the labels and their values in separate columns. would
it make more sense to switch the label column to value column name, shrinking
the tbl's size?