---
title: "Introduction to popler"
author: "Aldo Compagnoni"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The popler R package allows browsing and querying population data collected at `Long Term Ecological Research (LTER) network` sites located across the United States of America. A subset of the population data from the LTER network is now contained in an online database called popler. The popler R package is an interface with this online database, allowing users to:

- explore *what* type and *how much* population data is contained in the popler database
- download data contained in the popler database


## Installation

The popler R package is currently in the development phase, and it should be downloaded directly from its [GitHub page](https://github.com/AldoCompagnoni/popler). Before doing this, make sure to install the [Devtools R package](https://cran.r-project.org/web/packages/devtools/README.html). Once devtools is installed on your machine, install and load popler:

```r
devtools::install_github("AldoCompagnoni/popler",ref = "0.0.9001", build_vignettes = TRUE)
library("popler")
```

## Metadata: *what* type of data and *how much* data is contained in the popler database?

The LTER network provides data from thousands of research projects. The metadata of these projects allow understanding *what* and *how much* population data is provided by each project. The popler R package provides three functions to explore these metadata.

### dictionary()

`dictionary()` shows:

- what are the variables contained in the metadata of each project, and their meaning 
- what data these variables contain.

To see metadata variables and their meaning:  

```r
dictionary()
```

To show what data each variable actually contains, specify one or more variable:

```r
dictionary("phylum")
dictionary(vars = c("lterid", "duration_years") )
```

### browse()

`browse()` accesses and subsets the popler metadata table directly. Calling the function returns the raw metadata table:

```r
metadata_table <- browse()
```

This metadata table can be subset by specifying a logical statement. This is useful to focus on datasets of interest.

```r
sevilleta      <- browse(lterid == "SEV")
poa_metadata   <- browse(genus == "Poa")
```

#### The keyword binary operator, `%=%`

The projects carried out within the LTER network tackle a striking variety of research topics. Therefore, searching projects based on keywords can provide decisive advantages. The keyword binary operator `%=%` facilitates subsetting the metadata table by matching one or more keywords. In particular, `%=%` matches one or more character strings to one of the character variables shown by `dictionary()`. It is especially useful to match keywords with the title of projects:

```r
parasites       <- browse(title %=% "parasit")
parasite_npp    <- browse(title %=% c("parasit","npp"), trim = FALSE)
```

## Download data

Once you identified one or more datasets of interest, download their raw data using `get_data()`. You can download data in three ways:

1. By providing an object created subsetting the metadata table using `browse()` 
1. By further subsetting an object created through `browse()`
1. By subsetting the popler database directly through `get_data()`

First, you can download data by providing an object created through `browse()`. In the example below, the code returns all population data concerning species of the genus *Poa*: 

```r
poa_data      <- get_data(poa_metadata)
```

Second, you can further subset objects created through `browse()`. In the code below, popler downloads data concerning the genus *Poa* collected after the year 2008.

```r
poa_data_09   <- get_data(poa_metadata, year > 2008)
```

Third, you can directly provide a logical statement to `get_data()`:

```r
parasite_data         <- get_data(subset = proj_metadata_key == 25)
```
